# Site settings
title: Jarlath Holleran's Blog
email: jarlath.holleran@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  This blog is used to document useful and interesting information that I 
  have found working as a Software Developer. It is also contains Articles 
  and How To guides about various technologies.
baseurl: "/blog" # the subpath of your site, e.g. /blog/
url: "http://jholleran.github.io" # the base hostname & protocol for your site
twitter_username: JarlathHolleran
github_username:  jholleran

# Build settings
markdown: kramdown
